const RESPONSES = {
  en: {
    cpu: `The CPU (Central Processing Unit) is the brain of your computer. It executes instructions from programs by performing basic arithmetic, logic, control, and I/O operations. Modern CPUs have multiple cores, allowing parallel processing. For gaming, look for high single-core performance; for content creation, more cores help.`,
    ram: `RAM (Random Access Memory) is your computer's short-term memory. It stores data that the CPU is actively using, allowing for fast access times. More RAM allows more applications to run simultaneously. DDR5 is the latest standard, offering higher bandwidth than DDR4. Dual-channel mode doubles memory bandwidth.`,
    gpu: `The GPU (Graphics Processing Unit) renders images, videos, and animations. Modern GPUs have thousands of cores for parallel computation, making them essential for gaming, 3D rendering, and AI workloads. VRAM is GPU-specific memory — more VRAM handles higher resolution textures.`,
    ssd: `SSDs (Solid State Drives) use flash memory for storage, offering dramatically faster read/write speeds vs HDDs. NVMe SSDs use the PCIe interface for speeds up to 7,000 MB/s — that's 10× faster than SATA SSDs. They have no moving parts, making them more durable and silent.`,
    motherboard: `The motherboard is the main circuit board connecting all components. It houses the CPU socket, RAM slots, PCIe slots for the GPU, and storage interfaces. The chipset determines compatibility with CPUs and features. Form factors include ATX, Micro-ATX, and Mini-ITX.`,
    psu: `The PSU (Power Supply Unit) converts AC power from the wall into DC power for components. Efficiency rating (80 PLUS Bronze/Silver/Gold/Platinum) indicates power conversion efficiency. Always choose a PSU with 20-30% headroom above your system's calculated power draw.`,
    cooling: `PC cooling removes heat generated by components. Air coolers use heatsinks and fans; liquid AIO coolers use liquid-filled radiators for better thermal performance. Thermal paste between the CPU and cooler is critical for efficient heat transfer. Proper case airflow channels cool air over components.`,
    default: `Great question! PC hardware is a fascinating topic. Each component plays a vital role in system performance. Would you like me to explain any specific component in detail? I can cover CPUs, GPUs, RAM, storage, motherboards, PSUs, or cooling systems.`,
  },
  ar: {
    cpu: `المعالج (CPU) هو عقل حاسبك. ينفذ تعليمات البرامج عبر إجراء العمليات الحسابية والمنطقية والتحكم وعمليات الإدخال/الإخراج. تمتلك المعالجات الحديثة نوى متعددة تتيح المعالجة المتوازية. للألعاب، ابحث عن أداء النواة المفردة العالي؛ لإنشاء المحتوى، النوى الإضافية مفيدة.`,
    ram: `الذاكرة العشوائية (RAM) هي الذاكرة قصيرة الأمد لحاسبك. تخزن البيانات التي يستخدمها المعالج بنشاط، مما يتيح أوقات وصول سريعة. المزيد من الذاكرة يتيح تشغيل تطبيقات أكثر في آنٍ واحد. DDR5 هو أحدث معيار، يوفر عرض نطاق ترددي أعلى من DDR4. وضع القناة المزدوجة يضاعف عرض النطاق.`,
    gpu: `معالج الرسوميات (GPU) يعرض الصور والفيديوهات والرسوم المتحركة. تمتلك معالجات الرسوميات الحديثة آلاف النوى للحوسبة المتوازية، مما يجعلها أساسية للألعاب والتصيير ثلاثي الأبعاد وأعباء الذكاء الاصطناعي. VRAM هي ذاكرة خاصة بـGPU — المزيد منها يتعامل مع نسيج دقة أعلى.`,
    ssd: `محركات الحالة الصلبة (SSD) تستخدم ذاكرة الفلاش للتخزين، وتوفر سرعات قراءة/كتابة أسرع بكثير من HDD. تستخدم محركات NVMe واجهة PCIe بسرعات تصل إلى 7,000 ميجابايت/ثانية — أسرع 10 مرات من SATA SSD. لا تحتوي على أجزاء متحركة، مما يجعلها أكثر متانة وصمتاً.`,
    motherboard: `اللوحة الأم هي لوحة الدوائر الرئيسية التي تربط جميع المكونات. تحتوي على مقبس المعالج وفتحات الذاكرة وفتحات PCIe لبطاقة الرسوميات وواجهات التخزين. يحدد الشرائح الدقيقة التوافق مع المعالجات والميزات. تشمل عوامل الشكل ATX وMicro-ATX وMini-ITX.`,
    psu: `وحدة إمداد الطاقة (PSU) تحول طاقة التيار المتردد من الحائط إلى طاقة تيار مستمر للمكونات. يشير تقييم الكفاءة (80 PLUS برونزي/فضي/ذهبي/بلاتيني) إلى كفاءة تحويل الطاقة. اختر دائماً PSU بهامش 20-30% فوق استهلاك نظامك المحسوب.`,
    cooling: `يزيل تبريد الحاسب الحرارة المتولدة من المكونات. المبردات الهوائية تستخدم المشتتات الحرارية والمراوح؛ مبردات السائل AIO تستخدم مشعات مملوءة بالسائل لأداء حراري أفضل. المعجون الحراري بين المعالج والمبرد حرج لنقل الحرارة الفعال.`,
    default: `سؤال رائع! أجهزة الحاسب موضوع رائع. كل مكون يؤدي دوراً حيوياً في أداء النظام. هل تريد مني شرح أي مكون محدد بالتفصيل؟ أستطيع تغطية المعالجات ومعالجات الرسوميات والذاكرة والتخزين واللوحات الأم ووحدات الطاقة أو أنظمة التبريد.`,
  },
};

export function getAIResponse(msg, lang = 'en') {
  const m = msg.toLowerCase();
  const r = RESPONSES[lang] || RESPONSES.en;
  if (m.includes('cpu') || m.includes('processor') || m.includes('معالج'))           return r.cpu;
  if (m.includes('ram') || m.includes('memory') || m.includes('ذاكرة'))              return r.ram;
  if (m.includes('gpu') || m.includes('graphics') || m.includes('رسوميات'))          return r.gpu;
  if (m.includes('ssd') || m.includes('storage') || m.includes('nvme') || m.includes('تخزين')) return r.ssd;
  if (m.includes('motherboard') || m.includes('mobo') || m.includes('لوحة'))         return r.motherboard;
  if (m.includes('psu') || m.includes('power') || m.includes('طاقة'))                return r.psu;
  if (m.includes('cooling') || m.includes('cooler') || m.includes('تبريد'))          return r.cooling;
  return r.default;
}
